//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddlewareChevyStar.ChevyStarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChevyStarService.OnlineSoap")]
    public interface OnlineSoap {
        
        // CODEGEN: Generating message contract since message GetCarsInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MiddlewareChevyStar.ChevyStarService.GetCarsInfoResponse GetCarsInfo(MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoResponse> GetCarsInfoAsync(MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest request);
        
        // CODEGEN: Generating message contract since message GetCarsInfoNewRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfoNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewResponse GetCarsInfoNew(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfoNew", ReplyAction="*")]
        System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewResponse> GetCarsInfoNewAsync(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest request);
        
        // CODEGEN: Generating message contract since message GetCarsInfoNewByGroupNameRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfoNewByGroupName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameResponse GetCarsInfoNewByGroupName(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfoNewByGroupName", ReplyAction="*")]
        System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameResponse> GetCarsInfoNewByGroupNameAsync(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Authenticate(string Username, string Password, string CompanyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AuthenticateAsync(string Username, string Password, string CompanyName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string companyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CarOnlinePosItemInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal vehicle_LatitudeField;
        
        private decimal vehicle_LongitudeField;
        
        private short vehicle_AngleField;
        
        private short vehicle_ColorField;
        
        private string vehicle_Tool_TipField;
        
        private string vehicle_LabelField;
        
        private byte vehicle_Drive_typeField;
        
        private string event_TimeField;
        
        private byte vehicle_Online_StatusField;
        
        private string rEGION_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Vehicle_Latitude {
            get {
                return this.vehicle_LatitudeField;
            }
            set {
                this.vehicle_LatitudeField = value;
                this.RaisePropertyChanged("Vehicle_Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Vehicle_Longitude {
            get {
                return this.vehicle_LongitudeField;
            }
            set {
                this.vehicle_LongitudeField = value;
                this.RaisePropertyChanged("Vehicle_Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short Vehicle_Angle {
            get {
                return this.vehicle_AngleField;
            }
            set {
                this.vehicle_AngleField = value;
                this.RaisePropertyChanged("Vehicle_Angle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short Vehicle_Color {
            get {
                return this.vehicle_ColorField;
            }
            set {
                this.vehicle_ColorField = value;
                this.RaisePropertyChanged("Vehicle_Color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Vehicle_Tool_Tip {
            get {
                return this.vehicle_Tool_TipField;
            }
            set {
                this.vehicle_Tool_TipField = value;
                this.RaisePropertyChanged("Vehicle_Tool_Tip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Vehicle_Label {
            get {
                return this.vehicle_LabelField;
            }
            set {
                this.vehicle_LabelField = value;
                this.RaisePropertyChanged("Vehicle_Label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte Vehicle_Drive_type {
            get {
                return this.vehicle_Drive_typeField;
            }
            set {
                this.vehicle_Drive_typeField = value;
                this.RaisePropertyChanged("Vehicle_Drive_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Event_Time {
            get {
                return this.event_TimeField;
            }
            set {
                this.event_TimeField = value;
                this.RaisePropertyChanged("Event_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public byte Vehicle_Online_Status {
            get {
                return this.vehicle_Online_StatusField;
            }
            set {
                this.vehicle_Online_StatusField = value;
                this.RaisePropertyChanged("Vehicle_Online_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string REGION_NAME {
            get {
                return this.rEGION_NAMEField;
            }
            set {
                this.rEGION_NAMEField = value;
                this.RaisePropertyChanged("REGION_NAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo;
        
        public GetCarsInfoRequest() {
        }
        
        public GetCarsInfoRequest(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo) {
            this.LoginInfo = LoginInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MiddlewareChevyStar.ChevyStarService.CarOnlinePosItemInfo[] GetCarsInfoResult;
        
        public GetCarsInfoResponse() {
        }
        
        public GetCarsInfoResponse(MiddlewareChevyStar.ChevyStarService.CarOnlinePosItemInfo[] GetCarsInfoResult) {
            this.GetCarsInfoResult = GetCarsInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNew", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DeviceID;
        
        public GetCarsInfoNewRequest() {
        }
        
        public GetCarsInfoNewRequest(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo, string DeviceID) {
            this.LoginInfo = LoginInfo;
            this.DeviceID = DeviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCarsInfoNewResult;
        
        public GetCarsInfoNewResponse() {
        }
        
        public GetCarsInfoNewResponse(string GetCarsInfoNewResult) {
            this.GetCarsInfoNewResult = GetCarsInfoNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNewByGroupName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewByGroupNameRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OriginIP;
        
        public GetCarsInfoNewByGroupNameRequest() {
        }
        
        public GetCarsInfoNewByGroupNameRequest(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo, string GroupName, string OriginIP) {
            this.LoginInfo = LoginInfo;
            this.GroupName = GroupName;
            this.OriginIP = OriginIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNewByGroupNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewByGroupNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCarsInfoNewByGroupNameResult;
        
        public GetCarsInfoNewByGroupNameResponse() {
        }
        
        public GetCarsInfoNewByGroupNameResponse(string GetCarsInfoNewByGroupNameResult) {
            this.GetCarsInfoNewByGroupNameResult = GetCarsInfoNewByGroupNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlineSoapChannel : MiddlewareChevyStar.ChevyStarService.OnlineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineSoapClient : System.ServiceModel.ClientBase<MiddlewareChevyStar.ChevyStarService.OnlineSoap>, MiddlewareChevyStar.ChevyStarService.OnlineSoap {
        
        public OnlineSoapClient() {
        }
        
        public OnlineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiddlewareChevyStar.ChevyStarService.GetCarsInfoResponse MiddlewareChevyStar.ChevyStarService.OnlineSoap.GetCarsInfo(MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest request) {
            return base.Channel.GetCarsInfo(request);
        }
        
        public MiddlewareChevyStar.ChevyStarService.CarOnlinePosItemInfo[] GetCarsInfo(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo) {
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest inValue = new MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest();
            inValue.LoginInfo = LoginInfo;
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoResponse retVal = ((MiddlewareChevyStar.ChevyStarService.OnlineSoap)(this)).GetCarsInfo(inValue);
            return retVal.GetCarsInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoResponse> MiddlewareChevyStar.ChevyStarService.OnlineSoap.GetCarsInfoAsync(MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest request) {
            return base.Channel.GetCarsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoResponse> GetCarsInfoAsync(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo) {
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest inValue = new MiddlewareChevyStar.ChevyStarService.GetCarsInfoRequest();
            inValue.LoginInfo = LoginInfo;
            return ((MiddlewareChevyStar.ChevyStarService.OnlineSoap)(this)).GetCarsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewResponse MiddlewareChevyStar.ChevyStarService.OnlineSoap.GetCarsInfoNew(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest request) {
            return base.Channel.GetCarsInfoNew(request);
        }
        
        public string GetCarsInfoNew(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo, string DeviceID) {
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest inValue = new MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.DeviceID = DeviceID;
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewResponse retVal = ((MiddlewareChevyStar.ChevyStarService.OnlineSoap)(this)).GetCarsInfoNew(inValue);
            return retVal.GetCarsInfoNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewResponse> MiddlewareChevyStar.ChevyStarService.OnlineSoap.GetCarsInfoNewAsync(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest request) {
            return base.Channel.GetCarsInfoNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewResponse> GetCarsInfoNewAsync(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo, string DeviceID) {
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest inValue = new MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.DeviceID = DeviceID;
            return ((MiddlewareChevyStar.ChevyStarService.OnlineSoap)(this)).GetCarsInfoNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameResponse MiddlewareChevyStar.ChevyStarService.OnlineSoap.GetCarsInfoNewByGroupName(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest request) {
            return base.Channel.GetCarsInfoNewByGroupName(request);
        }
        
        public string GetCarsInfoNewByGroupName(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo, string GroupName, string OriginIP) {
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest inValue = new MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.GroupName = GroupName;
            inValue.OriginIP = OriginIP;
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameResponse retVal = ((MiddlewareChevyStar.ChevyStarService.OnlineSoap)(this)).GetCarsInfoNewByGroupName(inValue);
            return retVal.GetCarsInfoNewByGroupNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameResponse> MiddlewareChevyStar.ChevyStarService.OnlineSoap.GetCarsInfoNewByGroupNameAsync(MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest request) {
            return base.Channel.GetCarsInfoNewByGroupNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameResponse> GetCarsInfoNewByGroupNameAsync(MiddlewareChevyStar.ChevyStarService.LoginInfo LoginInfo, string GroupName, string OriginIP) {
            MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest inValue = new MiddlewareChevyStar.ChevyStarService.GetCarsInfoNewByGroupNameRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.GroupName = GroupName;
            inValue.OriginIP = OriginIP;
            return ((MiddlewareChevyStar.ChevyStarService.OnlineSoap)(this)).GetCarsInfoNewByGroupNameAsync(inValue);
        }
        
        public bool Authenticate(string Username, string Password, string CompanyName) {
            return base.Channel.Authenticate(Username, Password, CompanyName);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateAsync(string Username, string Password, string CompanyName) {
            return base.Channel.AuthenticateAsync(Username, Password, CompanyName);
        }
    }
}
